jupyterhub:
  proxy:
    secretToken: # SECRET TOKEN GOES HERE

  # comment this out if not using github authentication
  # auth:
  #   type: github
  #   github:
  #     clientId: "2cb5e09d5733ff2e6ae3"
  #     clientSecret: <SECRET>
  #     callbackUrl: "http://pangeo.pydata.org/hub/oauth_callback"
  #   admin:
  #     access: true
  #     users:
  #       - apawloski
