---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pangeo BinderHub Deployment - IAM prerequisites'

Resources:
  AWSServiceRoleForAmazonEKS:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref NodeInstanceRole

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

Outputs:
  WorkerNodeIAMRole:
    Description: The worker node IAM role (used by aws-auth-cm.yaml)
    Value: !GetAtt NodeInstanceRole.Arn

  WorkerNodeInstanceProfile:
    Description: The worker node IAM instance profile
    Value: !GetAtt NodeInstanceProfile.Arn

  ClusterServiceRole:
    Description: THe IAM role used by the EKS cluster to interact with AWS API
    Value: !GetAtt AWSServiceRoleForAmazonEKS.Arn
