---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pangeo BinderHub Deployment'

Parameters:
  TemplateBucket:
    Description: The S3 bucket (and prefix, if used) where cloudformation tempaltes are located.
    Type: String

  ClusterName:
    Description: The cluster name provided when the cluster was created. If it is incorrect, nodes will not be able to join the cluster.
    Type: String

  VpcBlock:
    Type: String
    Default: 192.168.0.0/16
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.

  Subnet01Block:
    Type: String
    Default: 192.168.64.0/18
    Description: CidrBlock for subnet 01 within the VPC

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "EKS Cluster"
        Parameters:
          - ClusterName
      -
        Label:
          default: "Worker Network Configuration"
        Parameters:
          - VpcBlock
          - Subnet01Block

Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - "https://s3.amazonaws.com/${TemplateBucket}/01-iam-creation.yaml"
      - { Bucket: !Ref TemplateBucket }

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - "https://s3.amazonaws.com/${TemplateBucket}/02-networking.yaml"
      - { Bucket: !Ref TemplateBucket }
      Parameters:
        ClusterName: !Ref ClusterName
        VpcBlock: !Ref VpcBlock
        Subnet01Block: !Ref Subnet01Block

  EKSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - "https://s3.amazonaws.com/${TemplateBucket}/03-eks-master.yaml"
      - { Bucket: !Ref TemplateBucket }
      Parameters:
        ClusterName: !Ref ClusterName
        ClusterServiceRole: !GetAtt IAMStack.Outputs.ClusterServiceRole
        ClusterSubnets: !GetAtt VPCStack.Outputs.SubnetIds
        ControlPlaneSecurityGroups: !GetAtt VPCStack.Outputs.ControlPlaneSecurityGroups

Outputs:
  WorkerNodeIAMRole:
    Description: The ARN of the worker node IAM role (used by aws-auth-cm.yaml)
    Value: !GetAtt IAMStack.Outputs.WorkerNodeIAMRole
    Export:
      Name: !Sub "${AWS::StackName}-WorkerNode-IAMRole"

  WorkerNodeInstanceProfile:
    Description: The ARN of the worker node IAM role (used by aws-auth-cm.yaml)
    Value: !GetAtt IAMStack.Outputs.WorkerNodeInstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-WorkerNode-InstanceProfile"

  SubnetIds:
    Description: All subnets in the VPC
    Value: !GetAtt VPCStack.Outputs.SubnetIds
    Export:
      Name: !Sub "${AWS::StackName}-VPC-Subnets"

  NodeSecurityGroups:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !GetAtt VPCStack.Outputs.NodeSecurityGroups
    Export:
      Name: !Sub "${AWS::StackName}-EKSNode-SGs"

  VpcId:
    Description: The VPC Id
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
